// Tutorials — All tutorial card data (8 chapters)
var GitTutorial = window.GitTutorial || {};

(function() {
  'use strict';

  var tutorials = [
    // Chapter 1: Git 是什么
    {
      id: 'ch1-what',
      chapter: 1,
      title: 'Git 是什么',
      content: [
        '## Git 是什么',
        '',
        'Git 是一个**分布式版本控制系统**。简单说，它帮你记录文件的每一次修改，让你可以随时回退到任意历史版本。',
        '',
        '**核心思想：快照，不是差异。**',
        '',
        '很多版本控制系统（如 SVN）存储的是「每次改了什么」（差异补丁）。Git 不同——它每次保存的是**整个项目的快照**（snapshot），像是给所有文件拍了一张照片。',
        '',
        '但这不意味着 Git 每次都复制一份完整文件。Git 用了一个巧妙的设计：',
        '- 没有变化的文件，Git 只存储一个指向上次快照的**引用**',
        '- 只有变化的文件，Git 才存储新的内容',
        '',
        '所以 Git 的存储效率很高，同时又能瞬间切换到任意版本。',
        '',
        '> Git 的设计哲学：**一切都可追溯，一切皆可回退。**'
      ].join('\n'),
      task: null
    },
    {
      id: 'ch1-objects',
      chapter: 1,
      title: 'Git 对象模型',
      content: [
        '## Git 对象模型：blob、tree、commit',
        '',
        'Git 的底层是三种对象，存在 `.git/objects/` 目录下：',
        '',
        '### blob（文件内容）',
        '存储文件的具体内容。一个 blob 就是一份文件数据，**不包含文件名**。',
        '',
        '### tree（目录结构）',
        '存储目录的信息：哪些文件名对应哪些 blob，哪些子目录对应哪些 tree。',
        '一个 tree 就是一张「文件名 → blob」的映射表。',
        '',
        '### commit（提交）',
        '存储一次提交的全部信息：',
        '- 指向一个 tree（这次提交的项目快照）',
        '- 指向父 commit（上一次提交）',
        '- 作者、时间、提交信息',
        '',
        '```',
        'commit -> tree -> blob',
        '  |',
        'parent commit -> tree -> blob',
        '```',
        '',
        '每个对象用 **SHA-1 哈希值**作为唯一标识（如 `a1b2c3d`）。这就是为什么 Git 能保证数据完整性——内容变了，哈希就变了。'
      ].join('\n'),
      task: null
    },
    {
      id: 'ch1-areas',
      chapter: 1,
      title: '四个区域',
      content: [
        '## Git 的四个区域',
        '',
        '这是理解 Git 工作流的关键。看看上方的四个区域：',
        '',
        '### 1. Working Directory（工作区）',
        '你实际编辑文件的地方。你用编辑器改代码，改的就是工作区的文件。',
        '',
        '### 2. Staging Area / Index（暂存区）',
        '一个「准备区」。你选择哪些修改要放进下一次提交。`git add` 就是把文件放进暂存区。',
        '',
        '### 3. Local Repository（本地仓库）',
        '提交历史存在这里。`git commit` 就是把暂存区的内容打包成一个快照，存进本地仓库。',
        '',
        '### 4. Remote Repository（远程仓库）',
        '服务器上的仓库（如 GitHub）。`git push` 把本地提交推到远程，`git pull` 把远程更新拉到本地。',
        '',
        '```',
        '工作区 --git add--> 暂存区 --git commit--> 本地仓库 --git push--> 远程仓库',
        '                       ^                                              |',
        '                       └──────────────── git pull ─────────────────────┘',
        '```',
        '',
        '> **暂存区的存在意义**：让你可以精确控制每次提交包含哪些修改。不用每次都把所有改动一起提交。'
      ].join('\n'),
      task: null
    },

    // Chapter 2: 初始化与配置
    {
      id: 'ch2-init',
      chapter: 2,
      title: 'git init',
      content: [
        '## git init — 初始化仓库',
        '',
        '`git init` 在当前目录创建一个 `.git` 隐藏文件夹，这个文件夹就是 Git 仓库的全部。',
        '',
        '`.git` 目录包含：',
        '- `objects/` — 所有 blob、tree、commit 对象',
        '- `refs/` — 分支和标签的指针',
        '- `HEAD` — 指向当前分支',
        '- `index` — 暂存区',
        '- `config` — 仓库级配置',
        '',
        '运行 `git init` 后，你的目录就变成了一个 Git 仓库。之后所有的版本控制操作都在这个目录下进行。',
        '',
        '**试试看**：在终端输入 `git init`，观察上方「工作区」的变化。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git init</code>' },
      highlights: ['init']
    },
    {
      id: 'ch2-config',
      chapter: 2,
      title: 'git config',
      content: [
        '## git config — 配置用户信息',
        '',
        'Git 需要知道「你是谁」才能记录提交的作者信息。',
        '',
        '**设置用户名和邮箱：**',
        '```',
        'git config user.name "你的名字"',
        'git config user.email "your@email.com"',
        '```',
        '',
        '**查看当前配置：**',
        '```',
        'git config user.name',
        'git config user.email',
        '```',
        '',
        '这三个配置级别：',
        '- `--local`（默认）— 只对当前仓库生效，存在 `.git/config`',
        '- `--global` — 对当前用户的所有仓库生效，存在 `~/.gitconfig`',
        '- `--system` — 对所有用户生效',
        '',
        '```',
        'git config --global user.name "你的名字"',
        'git config --global user.email "your@email.com"',
        '```',
        '',
        '> **建议**：用 `--global` 设置你的名字和邮箱，这样每个新仓库都会自动使用。'
      ].join('\n'),
      task: null,
      highlights: []
    },
    {
      id: 'ch2-touch',
      chapter: 2,
      title: '创建文件',
      content: [
        '## 创建文件',
        '',
        '在使用 Git 之前，我们先创建一些文件。',
        '',
        '`touch <filename>` 是一个 Unix 命令，用来创建空文件。在本教程的模拟终端中也可以使用。',
        '',
        '其他可用的辅助命令：',
        '- `echo "内容" > 文件名` — 创建文件并写入内容',
        '- `cat 文件名` — 查看文件内容',
        '',
        '这些不是 git 命令，但它们帮我们准备 git 要管理的文件。',
        '',
        '**试试看**：先创建文件，再用 echo 写入内容'
      ].join('\n'),
      task: { prompt: '先输入 <code>touch readme.md</code>，再输入 <code>echo "hello world" > readme.md</code>' },
      highlights: []
    },

    // Chapter 3: 日常基础
    {
      id: 'ch3-add',
      chapter: 3,
      title: 'git add',
      content: [
        '## git add — 暂存你的修改',
        '',
        '`git add <file>` 把文件从工作区移到暂存区。',
        '',
        '暂存区（Index）是 Git 特有的概念。它是一个「预提交区」——你可以选择性地把某些修改放进去，而不是把所有改动一次性提交。',
        '',
        '**用法：**',
        '- `git add file.txt` — 暂存单个文件',
        '- `git add .` — 暂存所有修改',
        '- `git add *.js` — 暂存所有 .js 文件',
        '',
        '执行 `git add` 后，看看上方区域的变化——文件应该从「工作区」出现在「暂存区」了。',
        '',
        '> **底层原理**：`git add` 会把文件内容计算 SHA-1 哈希，存为 blob 对象到 `.git/objects/`，并更新 `.git/index` 文件。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git add readme.md</code>' },
      highlights: ['add']
    },
    {
      id: 'ch3-status',
      chapter: 3,
      title: 'git status',
      content: [
        '## git status — 查看状态',
        '',
        '`git status` 显示工作区和暂存区的当前状态。',
        '',
        '它会告诉你：',
        '- 哪些文件**已暂存**（准备提交）',
        '- 哪些文件**已修改但未暂存**',
        '- 哪些文件**未跟踪**（新文件，Git 还不知道它的存在）',
        '',
        '这是你最常用的命令之一。当你不确定当前状态时，先跑一下 `git status`。',
        '',
        '**试试看**：创建了文件之后，运行 `git status` 看看输出。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git status</code>' },
      highlights: []
    },
    {
      id: 'ch3-commit',
      chapter: 3,
      title: 'git commit',
      content: [
        '## git commit — 提交更改',
        '',
        '`git commit -m "提交信息"` 把暂存区的内容打包成一个**提交**（commit），存入本地仓库。',
        '',
        '一次提交就是一份**项目快照**——记录了这一刻所有文件的状态。',
        '',
        '**提交信息很重要**。好的提交信息应该：',
        '- 简洁描述做了什么（不是怎么做的）',
        '- 用祈使语气：「Add login feature」而不是「Added login feature」',
        '- 第一行不超过 50 字符',
        '',
        '```',
        'git add .',
        'git commit -m "Add readme file"',
        '```',
        '',
        '提交后，看看上方「本地仓库」区域——你的第一个 commit 出现了！',
        '',
        '> **底层原理**：commit 会创建一个 commit 对象（包含 tree 指针、父 commit 指针、作者信息），然后更新分支指针指向这个新 commit。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git commit -m "Add readme"</code>' },
      highlights: ['commit']
    },
    {
      id: 'ch3-diff',
      chapter: 3,
      title: 'git diff',
      content: [
        '## git diff — 查看差异',
        '',
        '`git diff` 显示文件的具体修改内容。它逐行比较两个版本，告诉你**改了什么**。',
        '',
        '**三种用法：**',
        '- `git diff` — 比较**工作区 vs 暂存区**（你改了但还没 add 的内容）',
        '- `git diff --staged` — 比较**暂存区 vs 最后一次 commit**（你 add 了但还没 commit 的内容）',
        '- `git diff file.txt` — 只看某个文件的差异',
        '',
        '输出格式：',
        '```',
        'diff --git a/readme.md b/readme.md',
        '- 旧行（被删除的）',
        '+ 新行（被添加的）',
        '```',
        '',
        '**先做修改，再看差异：**',
        '用 `echo "新的内容" > readme.md` 给文件写入新内容，然后运行 `git diff` 看看改了什么。'
      ].join('\n'),
      task: { prompt: '先用 <code>echo "Hello Git" > readme.md</code> 修改文件，然后输入 <code>git diff</code>' },
      highlights: []
    },
    {
      id: 'ch3-log',
      chapter: 3,
      title: 'git log',
      content: [
        '## git log — 查看提交历史',
        '',
        '`git log` 显示从最新到最早的提交记录。',
        '',
        '每条记录包含：',
        '- commit hash（唯一标识）',
        '- 作者和时间',
        '- 提交信息',
        '',
        '**常用选项：**',
        '- `git log -n 3` — 只看最近 3 条',
        '- `git log --oneline` — 简洁模式（一行一条）',
        '',
        '试试看，你刚才的 commit 应该出现在历史里了。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git log</code>' },
      highlights: []
    },

    // Chapter 4: 分支操作
    {
      id: 'ch4-branch',
      chapter: 4,
      title: 'git branch',
      content: [
        '## git branch — 分支操作',
        '',
        '分支是 Git 最强大的功能之一。',
        '',
        '**什么是分支？**',
        '分支就是一个指向某个 commit 的**可移动指针**。创建分支就是创建一个新指针，非常轻量（只是一个 41 字节的文件）。',
        '',
        '**用法：**',
        '- `git branch` — 列出所有分支',
        '- `git branch dev` — 创建名为 dev 的新分支',
        '- `git branch -d dev` — 删除分支',
        '',
        '创建分支时，新分支指向当前 commit。两个分支共享之前的历史，之后各自独立发展。',
        '',
        '```',
        'main:    A -- B -- C',
        '                    \\',
        'dev:                 D -- E',
        '```',
        '',
        '**试试看**：创建一个 `dev` 分支'
      ].join('\n'),
      task: { prompt: '请输入: <code>git branch dev</code>' },
      highlights: []
    },
    {
      id: 'ch4-checkout',
      chapter: 4,
      title: 'git checkout',
      content: [
        '## git checkout — 切换分支',
        '',
        '`git checkout <branch>` 切换到指定分支。',
        '',
        '切换分支时，Git 会：',
        '1. 更新 HEAD 指向新分支',
        '2. 把工作区的文件更新为该分支指向的 commit 的内容',
        '',
        '**创建并切换（一步到位）：**',
        '`git checkout -b dev` — 创建 dev 分支并立即切换过去',
        '',
        '切换后，你的工作区会变成 dev 分支的内容。两个分支可以各自独立开发，互不影响。',
        '',
        '**试试看**：切换到 dev 分支'
      ].join('\n'),
      task: { prompt: '请输入: <code>git checkout dev</code>' },
      highlights: []
    },
    {
      id: 'ch4-switch',
      chapter: 4,
      title: 'git switch',
      content: [
        '## git switch — 切换分支（新命令）',
        '',
        '`git switch` 是 Git 2.23 引入的新命令，用来替代 `git checkout` 的分支切换功能。',
        '',
        '为什么？因为 `git checkout` 职责太多（切换分支、恢复文件、创建分支...），容易混淆。',
        '',
        '**用法：**',
        '- `git switch main` — 切换到 main 分支',
        '- `git switch -c feature` — 创建并切换到 feature 分支',
        '',
        '和 `git checkout` 的对应关系：',
        '- `git checkout dev` → `git switch dev`',
        '- `git checkout -b dev` → `git switch -c dev`',
        '',
        '**试试看**：切回 main 分支'
      ].join('\n'),
      task: { prompt: '请输入: <code>git switch main</code>' },
      highlights: []
    },
    {
      id: 'ch4-merge',
      chapter: 4,
      title: 'git merge',
      content: [
        '## git merge — 合并分支',
        '',
        '`git merge <branch>` 把指定分支的修改合并到当前分支。',
        '',
        '**快进合并（Fast-forward）**',
        '如果当前分支是目标分支的直接祖先，Git 只需要把指针往前移：',
        '```',
        '之前:  main → A ← dev → B → C',
        '之后:  main → A → B → C',
        '```',
        '',
        '**三方合并（3-way merge）**',
        '如果两个分支都有新提交，Git 需要找到共同祖先，然后合并两边的修改，创建一个新的「合并提交」：',
        '```',
        'main:  A -- B -- C -- M (merge commit)',
        '              \\      /',
        'dev:            D -- E',
        '```',
        '',
        '先在 dev 上做些修改和提交，然后切回 main 合并 dev，看看效果。'
      ].join('\n'),
      task: { prompt: '试试: 先切到 dev（<code>git switch dev</code>），创建文件并提交，再切回 main 合并' },
      highlights: ['commit']
    },
    {
      id: 'ch4-conflict',
      chapter: 4,
      title: '合并冲突',
      content: [
        '## 合并冲突',
        '',
        '当两个分支修改了同一个文件的同一位置，Git 无法自动合并，就会产生**冲突**。',
        '',
        '冲突标记长这样：',
        '```',
        '<<<<<<< HEAD',
        '当前分支的内容',
        '=======',
        '要合并的分支的内容',
        '>>>>>>> dev',
        '```',
        '',
        '解决步骤：',
        '1. 打开冲突文件，找到 `<<<<<<<` 标记',
        '2. 决定保留哪部分（或合并两者）',
        '3. 删除冲突标记',
        '4. `git add` 标记为已解决',
        '5. `git commit` 完成合并',
        '',
        '> 冲突不可怕。它只是 Git 在说：「这两个修改我没法自动合并，你来决定。」'
      ].join('\n'),
      task: null
    },

    // Chapter 5: 远程协作
    {
      id: 'ch5-ssh',
      chapter: 5,
      title: 'SSH Key',
      content: [
        '## SSH Key — 认证远程仓库',
        '',
        '要和 GitHub 等远程仓库通信，你需要证明「你是你」。SSH Key 是最常用的方式。',
        '',
        '**原理：**',
        '- 你生成一对密钥：**私钥**（留在本地）和**公钥**（上传到 GitHub）',
        '- GitHub 用公钥验证你的身份，你用私钥签名',
        '',
        '**步骤 1：生成密钥**',
        '```',
        'ssh-keygen -t rsa -C "your@email.com"',
        '```',
        '一路回车即可。默认生成在 `~/.ssh/id_rsa`。',
        '',
        '**步骤 2：复制公钥**',
        '```',
        'cat ~/.ssh/id_rsa.pub',
        '```',
        '复制输出的整行内容。',
        '',
        '**步骤 3：添加到 GitHub**',
        'GitHub → Settings → SSH and GPG keys → New SSH key → 粘贴公钥',
        '',
        '**步骤 4：测试连接**',
        '```',
        'ssh -T git@github.com',
        '```',
        '看到 `Hi username!` 就说明配置成功了。',
        '',
        '> 配置好 SSH 后，clone/push/pull 都可以用 `git@github.com:用户名/仓库.git` 格式的 URL，无需每次输入密码。'
      ].join('\n'),
      task: null
    },
    {
      id: 'ch5-clone',
      chapter: 5,
      title: 'git clone',
      content: [
        '## git clone — 克隆仓库',
        '',
        '`git clone <url>` 从远程仓库复制一份完整的项目到本地。',
        '',
        '它会：',
        '1. 下载远程仓库的所有对象（blob、tree、commit）',
        '2. 创建本地仓库',
        '3. 检出（checkout）默认分支（通常是 main）',
        '4. 设置远程地址为 `origin`',
        '',
        '克隆完成后，你拥有完整的项目历史，和远程仓库一模一样。这就是「分布式」的含义——每个人的本地都是一个完整的仓库。',
        '',
        '两种 URL 格式：',
        '- HTTPS：`https://github.com/user/repo.git`',
        '- SSH：`git@github.com:user/repo.git`（需要配置 SSH Key）',
        '',
        '> 注意：`git clone` 不能在已初始化的仓库中运行。它适用于从零开始获取一个远程项目。',
        '',
        '**试试看**：输入 `git clone`（模拟克隆一个示例仓库）'
      ].join('\n'),
      task: { prompt: '请输入: <code>git clone</code>' },
      highlights: []
    },
    {
      id: 'ch5-remote',
      chapter: 5,
      title: 'git remote',
      content: [
        '## git remote — 远程仓库',
        '',
        '远程仓库是托管在服务器上的 Git 仓库（如 GitHub、GitLab）。',
        '',
        '`git clone` 时会自动设置一个名为 `origin` 的远程仓库。你可以查看：',
        '```',
        'git remote -v',
        '```',
        '',
        '一条命令解释：',
        '- `origin` — 你 clone 来源的远程仓库的默认名字',
        '- 你可以添加多个远程仓库',
        '',
        '远程仓库和本地仓库通过 push/pull 同步。这就是团队协作的基础：',
        '每个人都有完整的本地仓库，通过远程仓库交换提交。',
        '',
        '上方的「远程仓库」区域会显示已推送到远程的提交记录。'
      ].join('\n'),
      task: null,
      highlights: []
    },
    {
      id: 'ch5-push',
      chapter: 5,
      title: 'git push',
      content: [
        '## git push — 推送到远程',
        '',
        '`git push origin main` 把本地 main 分支的提交推送到远程仓库。',
        '',
        '它做了什么：',
        '1. 把本地有而远程没有的 commit 发送到远程',
        '2. 更新远程分支指针',
        '',
        '**前提条件**：你的本地分支必须是远程分支的「后代」（即远程没有你遗漏的提交）。否则需要先 `git pull`。',
        '',
        '```',
        '本地:  A -- B -- C',
        '远程:  A -- B',
        '',
        'git push → 远程变成 A -- B -- C',
        '```',
        '',
        '**试试看**：push 你的 commit 到远程，观察上方「远程仓库」区域的变化。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git push origin main</code>' },
      highlights: ['push']
    },
    {
      id: 'ch5-fetch',
      chapter: 5,
      title: 'git fetch',
      content: [
        '## git fetch — 获取远程更新',
        '',
        '`git fetch origin` 从远程仓库下载新的提交，但**不会自动合并**到你的工作区。',
        '',
        '它只更新「远程跟踪分支」（如 `origin/main`），让你可以看到远程有什么新内容。',
        '',
        '```',
        'fetch 之前:  本地 main → C,  远程 main → E',
        'fetch 之后:  本地 main → C,  origin/main → E',
        '              （本地 main 还是 C，只是知道了远程有 E）',
        '```',
        '',
        '这是一个安全的操作——它不会改变你的任何文件。',
        '',
        '> `git pull` = `git fetch` + `git merge`。如果你想要更精确的控制，可以先 fetch，再决定是否 merge。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git fetch origin</code>' },
      highlights: []
    },
    {
      id: 'ch5-pull',
      chapter: 5,
      title: 'git pull',
      content: [
        '## git pull — 拉取并合并',
        '',
        '`git pull origin main` = `git fetch` + `git merge`。',
        '',
        '它会：',
        '1. 从远程下载新的提交（fetch）',
        '2. 自动合并到当前分支（merge）',
        '',
        '如果远程有你本地没有的提交，pull 会把它们合并进来。如果两边都有新提交，可能产生冲突。',
        '',
        '```',
        '本地:     A -- B -- C',
        '远程:     A -- B -- D -- E',
        '',
        'pull 之后: A -- B -- C -- M (merge)',
        '                  \\      /',
        '                   D -- E',
        '```',
        '',
        '日常开发中，开始工作前先 `git pull` 是个好习惯。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git pull origin main</code>' },
      highlights: []
    },

    // Chapter 6: 撤销与修正
    {
      id: 'ch6-reset',
      chapter: 6,
      title: 'git reset',
      content: [
        '## git reset — 重置',
        '',
        '`git reset` 是一个强大的撤销命令，有三种模式：',
        '',
        '### --soft（软重置）',
        '只移动 HEAD 指针。暂存区和工作区不变。',
        '用途：撤销 commit，但保留修改在暂存区（可以重新 commit）。',
        '',
        '### --mixed（默认）',
        '移动 HEAD + 清空暂存区。工作区不变。',
        '用途：撤销 commit 和 add，修改保留在工作区。',
        '',
        '### --hard（硬重置）',
        '移动 HEAD + 清空暂存区 + 恢复工作区。',
        '用途：彻底回到某个 commit 的状态。**危险操作，会丢失未提交的修改！**',
        '',
        '```',
        'git reset --soft HEAD~1   # 撤销最后一次 commit',
        'git reset --mixed HEAD~1  # 撤销 commit 和 add',
        'git reset --hard HEAD~1   # 彻底回退',
        '```'
      ].join('\n'),
      task: { prompt: '试试: <code>git reset --soft HEAD</code>（安全，只是演示）' },
      highlights: []
    },
    {
      id: 'ch6-revert',
      chapter: 6,
      title: 'git revert',
      content: [
        '## git revert — 撤销提交',
        '',
        '`git revert <commit-hash>` 创建一个**新的提交**，内容是「撤销指定 commit 的修改」。',
        '',
        '和 `reset` 的区别：',
        '- `reset` 是**删除**历史（改写已有的 commit）',
        '- `revert` 是**新增**历史（创建一个「反向操作」的 commit）',
        '',
        '```',
        '原来:  A -- B -- C',
        'revert B:  A -- B -- C -- B\'',
        '```',
        '',
        'revert 更安全，因为它不改写历史。在已经 push 到远程的 commit 上，应该用 revert 而不是 reset。',
        '',
        '> **黄金法则**：如果 commit 已经 push 到远程并被其他人使用了，**永远用 revert，不用 reset**。'
      ].join('\n'),
      task: { prompt: '如果有 commit，试试: <code>git revert HEAD</code>' },
      highlights: ['commit']
    },
    {
      id: 'ch6-restore',
      chapter: 6,
      title: 'git restore',
      content: [
        '## git restore — 恢复文件',
        '',
        '`git restore <file>` 把文件恢复到最后一次 commit 的状态（丢弃工作区的修改）。',
        '',
        '这是 Git 2.23 引入的新命令，用来替代 `git checkout -- <file>`（那个语法太容易和切换分支混淆了）。',
        '',
        '**用法：**',
        '- `git restore file.txt` — 恢复工作区的文件',
        '- `git restore --staged file.txt` — 取消暂存（从暂存区移除，但保留工作区修改）',
        '',
        '和 `git reset` 的区别：',
        '- `reset` 操作的是 commit / 分支指针',
        '- `restore` 操作的是单个文件',
        '',
        '**试试看**：修改一个文件，然后用 restore 恢复它。'
      ].join('\n'),
      task: { prompt: '试试: 修改文件后运行 <code>git restore readme.md</code>' },
      highlights: []
    },
    {
      id: 'ch6-checkout-file',
      chapter: 6,
      title: 'checkout 恢复文件',
      content: [
        '## git checkout 恢复文件（旧语法）',
        '',
        '在 Git 2.23 之前，恢复文件用的是：',
        '```',
        'git checkout -- <file>',
        '```',
        '',
        '这个命令会把工作区的文件恢复到暂存区（如果暂存区有内容）或最后一次 commit 的状态。',
        '',
        '因为 `git checkout` 同时用于切换分支和恢复文件，容易搞混。所以新版本拆分成了：',
        '- `git switch` — 切换分支',
        '- `git restore` — 恢复文件',
        '',
        '但你仍然会看到很多项目和教程使用旧语法，了解一下有好处。'
      ].join('\n'),
      task: null
    },

    // Chapter 7: 进阶工具
    {
      id: 'ch7-rebase',
      chapter: 7,
      title: 'git rebase',
      content: [
        '## git rebase — 变基',
        '',
        '`git rebase <branch>` 把当前分支的提交「移植」到目标分支的最新提交之后。',
        '',
        '和 merge 的区别：',
        '```',
        'merge:   A -- B -- C -- M (merge commit)',
        '              \\      /',
        'dev:            D -- E',
        '',
        'rebase:  A -- B -- D\' -- E\' (线性历史)',
        '```',
        '',
        'rebase 让提交历史变成一条直线，更整洁。',
        '',
        '**黄金法则**：**不要 rebase 已经 push 到远程的 commit！**',
        '',
        'rebase 会改写 commit 的哈希值。如果其他人已经基于旧 commit 工作了，rebase 会导致混乱。',
        '',
        '> rebase 适合在 push 之前整理本地提交。merge 适合合并公共分支。'
      ].join('\n'),
      task: { prompt: '如果有两个分支，试试: <code>git rebase main</code>' },
      highlights: ['commit']
    },
    {
      id: 'ch7-stash',
      chapter: 7,
      title: 'git stash',
      content: [
        '## git stash — 临时保存',
        '',
        '`git stash` 把当前工作区和暂存区的修改「藏起来」，让工作区恢复干净。',
        '',
        '场景：你在 feature 分支开发到一半，突然需要切到 main 修复 bug。但你的修改还没法 commit。',
        '',
        '**用法：**',
        '- `git stash` — 保存当前修改',
        '- `git stash list` — 查看所有 stash',
        '- `git stash pop` — 恢复最近一次 stash 并删除',
        '- `git stash apply` — 恢复但不删除',
        '',
        '```',
        'git stash         # 藏起来',
        'git switch main   # 切到 main 修 bug',
        'git switch feature # 切回来',
        'git stash pop     # 恢复之前的工作',
        '```',
        '',
        '**试试看**：修改文件后 stash，看看工作区是否变干净。'
      ].join('\n'),
      task: { prompt: '试试: 修改文件后运行 <code>git stash</code>' },
      highlights: []
    },
    {
      id: 'ch7-cherry-pick',
      chapter: 7,
      title: 'git cherry-pick',
      content: [
        '## git cherry-pick — 拣选提交',
        '',
        '`git cherry-pick <commit-hash>` 把某个 commit 的修改「复制」到当前分支。',
        '',
        '场景：你在 dev 分支修了一个 bug，但不想合并整个 dev，只想把这个修复拿到 main 上。',
        '',
        '```',
        'dev:   A -- B -- C -- D (D 是 bug fix)',
        'main:  A -- B',
        '',
        'git switch main',
        'git cherry-pick D',
        'main:  A -- B -- D\'',
        '```',
        '',
        'cherry-pick 会创建一个新的 commit（哈希不同），内容和原 commit 一样。',
        '',
        '> 注意：这是「复制」不是「移动」。dev 分支上的 D 仍然存在。'
      ].join('\n'),
      task: { prompt: '如果有其他分支的 commit，试试: <code>git cherry-pick &lt;hash&gt;</code>' },
      highlights: ['commit']
    },
    {
      id: 'ch7-tag',
      chapter: 7,
      title: 'git tag',
      content: [
        '## git tag — 标签',
        '',
        '`git tag v1.0` 给当前 commit 打一个标签。',
        '',
        '标签和分支类似，都是指向 commit 的指针。区别是：',
        '- **分支**会随着新 commit 移动',
        '- **标签**永远固定在创建时的 commit 上',
        '',
        '标签通常用于标记发布版本（v1.0, v2.0, ...）。',
        '',
        '**用法：**',
        '- `git tag` — 列出所有标签',
        '- `git tag v1.0` — 创建轻量标签',
        '',
        '**试试看**：给当前 commit 打个标签。'
      ].join('\n'),
      task: { prompt: '请输入: <code>git tag v1.0</code>' },
      highlights: []
    },
    {
      id: 'ch7-rm',
      chapter: 7,
      title: 'git rm',
      content: [
        '## git rm — 删除文件',
        '',
        '`git rm <file>` 从工作区和暂存区同时删除文件。',
        '',
        '和直接 `delete` 文件的区别：',
        '- 直接删除文件，Git 不知道你删了（需要 `git add` 来告诉它）',
        '- `git rm` 一步到位：删除文件 + 暂存删除操作',
        '',
        '如果只想从暂存区删除（保留工作区文件）：',
        '```',
        'git rm --cached <file>',
        '```',
        '',
        '这个命令常用于：不小心把文件 add 进去了，想从 Git 跟踪中移除它。',
        '',
        '**试试看**：用 `git rm` 删除一个文件。'
      ].join('\n'),
      task: { prompt: '试试: <code>git rm readme.md</code>' },
      highlights: []
    },

    // Chapter 8: 工作流总览
    {
      id: 'ch8-workflow',
      chapter: 8,
      title: '日常开发流程',
      content: [
        '## 日常开发流程',
        '',
        '一个典型的 Git 工作日：',
        '',
        '```',
        '# 1. 拉取最新代码',
        'git pull origin main',
        '',
        '# 2. 创建功能分支',
        'git switch -c feature/login',
        '',
        '# 3. 开发、提交',
        'git add .',
        'git commit -m "Add login form"',
        '',
        '# 4. 推送到远程',
        'git push origin feature/login',
        '',
        '# 5. 创建 Pull Request（在 GitHub 上）',
        '',
        '# 6. 代码审查后合并到 main',
        '',
        '# 7. 切回 main，拉取最新',
        'git switch main',
        'git pull origin main',
        '',
        '# 8. 删除功能分支',
        'git branch -d feature/login',
        '```',
        '',
        '核心循环就是：**修改 → add → commit → push → PR → merge**'
      ].join('\n'),
      task: null
    },
    {
      id: 'ch8-gitflow',
      chapter: 8,
      title: 'Git Flow',
      content: [
        '## Git Flow 工作流',
        '',
        'Git Flow 是一种流行的分支管理策略：',
        '',
        '- **main** — 永远是生产环境的代码',
        '- **develop** — 开发主线',
        '- **feature/*** — 功能分支，从 develop 分出',
        '- **release/*** — 发布准备分支',
        '- **hotfix/*** — 紧急修复分支',
        '',
        '```',
        'main:     A --------- M --------- R',
        '           \\         ^           ^',
        'dev:        D -- F -- D -- F --- D',
        '               ^    ^',
        'feature:      f1   f2',
        '```',
        '',
        '小团队可能不需要这么复杂。简单的策略：',
        '- main 保持可部署',
        '- 每个功能一个分支',
        '- 通过 PR 合并',
        '',
        '> 选择适合你团队的工作流，不要为了流程而流程。'
      ].join('\n'),
      task: null
    },
    {
      id: 'ch8-tips',
      chapter: 8,
      title: '常见问题',
      content: [
        '## 常见问题速查',
        '',
        '### 撤销最后一次 commit（保留修改）',
        '```',
        'git reset --soft HEAD~1',
        '```',
        '',
        '### 撤销已 push 的 commit',
        '```',
        'git revert <hash>',
        '```',
        '',
        '### 丢弃工作区所有修改',
        '```',
        'git restore .',
        '```',
        '',
        '### 查看某个文件的历史',
        '```',
        'git log -- <file>',
        '```',
        '',
        '### 暂存当前工作',
        '```',
        'git stash',
        '```',
        '',
        '### 合并分支（保留历史）',
        '```',
        'git merge <branch>',
        '```',
        '',
        '### 整理提交历史',
        '```',
        'git rebase -i HEAD~3',
        '```',
        '',
        '### 找出谁改了某行',
        '```',
        'git blame <file>',
        '```',
        '',
        '> 记住：**git status** 是你最好的朋友。不确定状态时，先看 status。'
      ].join('\n'),
      task: null
    }
  ];

  // Build chapters from flat list
  var chapters = [];
  var chapterNames = [
    'Git 是什么',
    '初始化与配置',
    '日常基础',
    '分支操作',
    '远程协作',
    '撤销与修正',
    '进阶工具',
    '工作流总览'
  ];

  for (var i = 0; i < chapterNames.length; i++) {
    var ch = {
      title: chapterNames[i],
      cards: []
    };
    for (var j = 0; j < tutorials.length; j++) {
      if (tutorials[j].chapter === i + 1) {
        ch.cards.push(tutorials[j]);
      }
    }
    chapters.push(ch);
  }

  // Expose
  GitTutorial.tutorials = tutorials;
  GitTutorial.chapters = chapters;
  window.GitTutorial = GitTutorial;
})();
